# Generated by Django 4.1.3 on 2023-01-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('private_room', '0001_initial'),
        ('private_message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reply', models.IntegerField(blank=True, null=True)),
                ('images', models.ImageField(null=True, upload_to='mess_img/')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='private_message.chat')),
                ('private_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='private_room.private_room')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
