# Generated by Django 4.1.3 on 2022-12-16 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 15, 2, 30, 550557)),
        ),
    ]
