# Generated by Django 4.1.3 on 2022-12-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_chat_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
