# Generated by Django 4.1.3 on 2022-12-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_message_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='static/images'),
        ),
    ]
