# Generated by Django 4.1.3 on 2022-12-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_message_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(null=True, upload_to='mess_img/'),
        ),
    ]
