# Generated by Django 4.1.3 on 2022-12-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_message_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
