# Generated by Django 4.1.3 on 2022-12-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
