# Generated by Django 4.1.3 on 2022-12-25 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_chat_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friend', models.BooleanField(default=False)),
                ('friend', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='Friend')),
            ],
        ),
    ]
