# Generated by Django 4.1.3 on 2022-12-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
