# Generated by Django 4.1.3 on 2022-12-26 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_user_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='host_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_friend', to=settings.AUTH_USER_MODEL, verbose_name='Host friend'),
        ),
    ]
