# Generated by Django 4.1.3 on 2023-01-04 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_private_room_message_private_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_room',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
