# Generated by Django 4.1.3 on 2023-01-04 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_private_room_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private_room',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='private_room',
            name='people',
        ),
        migrations.AddField(
            model_name='private_room',
            name='room_friends',
            field=models.ManyToManyField(blank=True, related_name='room_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
