# Generated by Django 4.1.3 on 2023-01-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_private_room_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_room',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
