# Generated by Django 4.1.3 on 2023-01-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_private_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_room',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
