# Generated by Django 4.1.3 on 2023-01-10 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='Friend'),
        ),
        migrations.AddField(
            model_name='friends',
            name='host_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_friend', to=settings.AUTH_USER_MODEL, verbose_name='Host friend'),
        ),
    ]
